server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/careapp}
    username: ${SPRING_DATASOURCE_USERNAME:careuser}
    password: ${SPRING_DATASOURCE_PASSWORD:carepass}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  auth:
    jwt:
      private-path: ${APP_AUTH_JWT_PRIVATE_PATH:/app/keys/jwt-private.pem}
      public-path: ${APP_AUTH_JWT_PUBLIC_PATH:/app/keys/jwt-public.pem}

management:
  endpoints:
    web.exposure.include: health,info,metrics,prometheus
