spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/careapp
    username: careuser
    password: carepass

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob.non_contextual_creation: true

  flyway:
    enabled: true
    schemas: public
    baseline-on-migrate: true

app:
  mysql:
    enabled: false
